In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


In [4]:
a = np.array([2,5,1,7,6,3,9,0,4])
a[1:5]

array([5, 1, 7, 6])

In [4]:
b = np.array([[9.0, 10.0, 6.0], [6.0,1.0,7.0]])
b

array([[ 9., 10.,  6.],
       [ 6.,  1.,  7.]])

In [5]:
n = np.array([1, 3.0, 0.004, -2])
n

array([ 1.   ,  3.   ,  0.004, -2.   ])

In [6]:
a.ndim

1

In [7]:
b.ndim

2

In [9]:
a.shape

(3,)

In [8]:
b.shape

(2, 3)

In [6]:
a.dtype

dtype('int32')

In [7]:
a.itemsize

4

In [8]:
a = np.array([1,2,3], dtype='int16')
a

array([1, 2, 3], dtype=int16)

In [9]:
a.itemsize

2

In [10]:
a.size

3

In [11]:
a.nbytes

6

In [25]:
b.nbytes

32

In [12]:
a.size*a.itemsize

6

In [13]:
len(a)

3

In [10]:
len(b)

2

In [116]:
a = np.array([2,5,1,7,6,3,9,0,4])

In [117]:
a[0]

2

In [118]:
a[3]

7

In [119]:
a[1:5]

array([5, 1, 7, 6])

In [121]:
np.array([1,2,3, 4])**2

array([ 1,  4,  9, 16], dtype=int32)

In [14]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [15]:
a[1, 5]

13

In [16]:
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [17]:
a[:, 2]

array([ 3, 10])

In [18]:
a[0, 1:-1:2]

array([2, 4, 6])

In [20]:
a[1, 5] = 20

In [22]:
a[:, 2] = [3,5]

In [23]:
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9,  5, 11, 12, 20, 14]])

In [24]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

### Initializing Different Types of Arays

In [129]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [130]:
np.arange(10)**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [112]:
np.arange(0, 15, 3)

array([ 0,  3,  6,  9, 12])

In [12]:
np.linspace(0, 3, 15)

array([0.        , 0.21428571, 0.42857143, 0.64285714, 0.85714286,
       1.07142857, 1.28571429, 1.5       , 1.71428571, 1.92857143,
       2.14285714, 2.35714286, 2.57142857, 2.78571429, 3.        ])

In [14]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
np.eye(2,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.]])

In [26]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
np.ones((4,3,2), dtype='int32')

array([[[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]]])

In [16]:
np.full((2,2), 30)

array([[30, 30],
       [30, 30]])

In [29]:
np.random.rand(4,2)

array([[0.1116018 , 0.4281243 ],
       [0.24421708, 0.59221708],
       [0.70009141, 0.640944  ],
       [0.86913773, 0.42700925]])

In [19]:
ar = np.array([[2,3], [4,5]])
ar

array([[2, 3],
       [4, 5]])

In [18]:
np.full_like(ar, 4)

array([[4, 4],
       [4, 4]])

In [31]:
np.full_like(b, 4)

array([[[4, 4],
        [4, 4]],

       [[4, 4],
        [4, 4]]])

In [32]:
np.random.randint(-4, 8, size=(3,3))

array([[-4, -2,  2],
       [ 6,  2,  6],
       [ 2, -2,  0]])

In [33]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [125]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [126]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [131]:
a = np.array([2,4,5])

In [132]:
np.diag(a)

array([[2, 0, 0],
       [0, 4, 0],
       [0, 0, 5]])

#### Repeat

In [127]:
np.array([2,4,6]*4)

array([2, 4, 6, 2, 4, 6, 2, 4, 6, 2, 4, 6])

In [20]:
np.repeat([2, 4, 6], 3)

array([2, 2, 2, 4, 4, 4, 6, 6, 6])

In [21]:
arr = np.array([[2, 4, 6]])
arr

array([[2, 4, 6]])

In [23]:
np.repeat(np.array([[2, 4, 6]]), 3, axis=0)

array([[2, 4, 6],
       [2, 4, 6],
       [2, 4, 6]])

In [22]:
r1 = np.repeat(arr,3,axis=0)
r1

array([[2, 4, 6],
       [2, 4, 6],
       [2, 4, 6]])

In [24]:
np.repeat(arr,3,axis=1)

array([[2, 2, 2, 4, 4, 4, 6, 6, 6]])

In [36]:
output = np.ones((5,5))
output

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [37]:
z = np.zeros((3,3))
z[1,1] = 9
z

array([[0., 0., 0.],
       [0., 9., 0.],
       [0., 0., 0.]])

In [39]:
output[1:-1, 1:-1] = z
output

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

### Be careful when copying arrays

In [40]:
a= np.array([1,2,3])
b = a.copy()
b[0] = 100
a

array([1, 2, 3])

In [41]:
b

array([100,   2,   3])

### Mathematics

In [40]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [43]:
a+2

array([3, 4, 5, 6])

In [44]:
a-2

array([-1,  0,  1,  2])

In [45]:
a*2

array([2, 4, 6, 8])

In [46]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [41]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [4]:
b = np.array([1,0,1,0])
b

array([1, 0, 1, 0])

In [5]:
a + b

array([2, 2, 4, 4])

In [50]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [51]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [52]:
np.tan(a)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128])

In [6]:
b = np.array([3,4,5,6])
b

array([3, 4, 5, 6])

In [91]:
a + b

array([ 4,  6,  8, 10])

In [92]:
a - b

array([-2, -2, -2, -2])

In [93]:
a*b

array([ 3,  8, 15, 24])

In [94]:
a/b

array([0.33333333, 0.5       , 0.6       , 0.66666667])

In [95]:
a**b

array([   1,   16,  243, 4096], dtype=int32)

In [96]:
a.dot(b)

50

In [157]:
np.dot(a, b)

50

In [97]:
a

array([1, 2, 3, 4])

In [98]:
b

array([3, 4, 5, 6])

In [99]:
1*3 + 2*4 + 3*5 + 4*6

50

#### Linear Algebra

In [17]:
a = np.array([[3, 5, 1], [6, 4, 9]])
a

array([[3, 5, 1],
       [6, 4, 9]])

In [18]:
b = np.array([[5,2], [7,9], [4, 3]])
b

array([[5, 2],
       [7, 9],
       [4, 3]])

In [23]:
c = np.array([[9, 1, 3], [10, 2, 7]])
c

array([[ 9,  1,  3],
       [10,  2,  7]])

In [25]:
d = np.array([[5,2, 3], [7,9, 2], [4, 3, 1]])
d

array([[5, 2, 3],
       [7, 9, 2],
       [4, 3, 1]])

In [26]:
np.dot(a, d)

array([[54, 54, 20],
       [94, 75, 35]])

In [24]:
np.dot(a, c)
a+b

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [20]:
np.matmul(a, b)

array([[54, 54],
       [94, 75]])

In [21]:
a.dot(b)

array([[54, 54],
       [94, 75]])

In [59]:
c = np.identity(3)
np.linalg.det(c)

1.0

In [60]:
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [28]:
p = np.array([2,5,1])
q = np.array([[4,2,7]])
np.matmul(p, q)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 1 is different from 3)

https://docs.scipy.org/doc/numpy/reference/routines.linalg.html

#### Statistics

In [31]:
x = np.array([1,3,4,6,-3,-2])

In [32]:
x.sum()

9

In [33]:
x.max()

6

In [34]:
x.min()

-3

In [35]:
x.mean()

1.5

In [36]:
x.std()

3.2015621187164243

In [37]:
np.sqrt(x)

C:\Users\User\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([1.        , 1.73205081, 2.        , 2.44948974,        nan,
              nan])

In [38]:
x.argmin()

4

In [39]:
x.argmax()

3

In [148]:
stats = np.array([[1,2,3], [4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [151]:
stats.sum(axis=0)

array([5, 7, 9])

In [152]:
np.sum(stats, axis=0)

array([5, 7, 9])

In [153]:
np.sum(stats, axis=1)

array([ 6, 15])

In [66]:
np.min(stats)

1

In [67]:
np.max(stats)

6

In [69]:
np.max(stats, axis=1)

array([3, 6])

In [70]:
np.max(stats, axis=0)

array([4, 5, 6])

#### Reorganizing Arrays

In [115]:
x = np.arange(0, 45, 3)
x

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42])

In [116]:
x.reshape(3, 5)

array([[ 0,  3,  6,  9, 12],
       [15, 18, 21, 24, 27],
       [30, 33, 36, 39, 42]])

In [120]:
x = np.arange(0, 45, 3)

In [121]:
x.resize(3,5)

In [122]:
x

array([[ 0,  3,  6,  9, 12],
       [15, 18, 21, 24, 27],
       [30, 33, 36, 39, 42]])

In [134]:
x.ravel()

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42])

In [137]:
c = np.array([4,5,6])
c

array([4, 5, 6])

In [139]:
c.resize(3,1)

In [140]:
c

array([[4],
       [5],
       [6]])

In [42]:
c = np.array([4,5,6])
c.resize(1,3)

In [43]:
c

array([[4, 5, 6]])

In [141]:
c = np.array([4,5,6, 7])
c.reshape(2, -1)

array([[4, 5],
       [6, 7]])

In [55]:
x = np.array([[1,2,3,4], [5,6,7,8]])
x

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [56]:
y = x.reshape(4,2)

In [57]:
y

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [58]:
x = np.array([[1,2,3,4], [5,6,7,8]])

In [60]:
x.reshape(4, -1)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [47]:
x.resize(4,2)

In [48]:
x

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [101]:
y.shape

(4, 2)

In [102]:
y.T

array([[1, 3, 5, 7],
       [2, 4, 6, 8]])

In [103]:
y.T.shape

(2, 4)

In [75]:
x1 = np.array([1,2,3,4])
x2 = np.array([5,6,7,8])
np.vstack([x1, x2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [5]:
x1 = [[2, 4, 3, 7], [2, 5, 3, 1]]
x2 = [1, 0, 9, 5]

In [6]:
np.vstack([x1, x2])

array([[2, 4, 3, 7],
       [2, 5, 3, 1],
       [1, 0, 9, 5]])

In [68]:
np.vstack([x1, x2, x2])

array([[2, 4, 3, 7],
       [2, 5, 3, 1],
       [1, 0, 9, 5],
       [1, 0, 9, 5]])

In [70]:
np.array(x1)

array([[2, 4, 3, 7],
       [2, 5, 3, 1]])

In [73]:
x3 = np.ones((2,3))
x3

array([[1., 1., 1.],
       [1., 1., 1.]])

In [74]:
np.hstack([x1, x3])

array([[2., 4., 3., 7., 1., 1., 1.],
       [2., 5., 3., 1., 1., 1., 1.]])

In [76]:
np.vstack([x1, x2, x1, x2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [61]:
h1 = np.ones((3,4))
h1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [62]:
h2 = np.zeros((3,2))
h2

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [80]:
np.hstack((h1, h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

In [8]:
x1 = [[2, 4, 3, 7], [2, 5, 3, 1]]
x2 = [[1, 0, 9, 5]]

In [11]:
np.concatenate((x1, x2), axis=0)

array([[2, 4, 3, 7],
       [2, 5, 3, 1],
       [1, 0, 9, 5]])

In [13]:
x3 = [[2,4], [7,5]]

In [14]:
np.concatenate((x1, x3), axis=1)

array([[2, 4, 3, 7, 2, 4],
       [2, 5, 3, 1, 7, 5]])

### Misc

In [87]:
filedata = np.genfromtxt('Cartwheeldata.csv', delimiter=',')
filedata=filedata.astype('int32')
filedata

array([[-2147483648, -2147483648, -2147483648, -2147483648, -2147483648,
        -2147483648, -2147483648, -2147483648, -2147483648, -2147483648,
        -2147483648, -2147483648],
       [          1,          56, -2147483648,           1, -2147483648,
                  1,          62,          61,          79, -2147483648,
                  1,           7],
       [          2,          26, -2147483648,           1, -2147483648,
                  1,          62,          60,          70, -2147483648,
                  1,           8],
       [          3,          33, -2147483648,           1, -2147483648,
                  1,          66,          64,          85, -2147483648,
                  1,           7],
       [          4,          39, -2147483648,           1, -2147483648,
                  0,          64,          63,          87, -2147483648,
                  1,          10],
       [          5,          27, -2147483648,           2, -2147483648,
                  0,  

#### Random

In [75]:
np.random.rand()

0.541670003513435

In [76]:
np.random.rand(3)

array([0.6432591 , 0.78715203, 0.81071309])

In [77]:
np.random.rand(2, 3)

array([[0.91757316, 0.74438045, 0.85259742],
       [0.19826903, 0.84990728, 0.48328816]])

In [81]:
np.random.randn(4)

array([ 2.43225203, -1.09931375, -0.76311341,  0.46116162])

In [83]:
np.random.standard_normal((2,4))  #-5 to 5

array([[ 0.32693229,  0.15654011, -0.83708242, -0.86318489],
       [ 0.72055276, -0.94472654,  1.03103145,  0.23610005]])

In [89]:
np.random.randint(25)

20

In [91]:
np.random.randint(1, 100, 10)

array([96, 44, 90, 13, 47, 16,  9, 46, 49, 20])

In [92]:
np.random.randint(1, 100, (3,3))

array([[25, 80, 42],
       [95, 82, 66],
       [64, 95, 55]])

In [94]:
np.random.random_sample(5)

array([0.11888634, 0.87646953, 0.09447431, 0.48614515, 0.21996786])

In [95]:
np.random.random_sample((3,3))

array([[0.51189786, 0.15339182, 0.0182916 ],
       [0.7026345 , 0.42682458, 0.79731571],
       [0.40621087, 0.29814825, 0.02253169]])

In [98]:
s = np.random.random_sample(10000)
np.mean(s)

0.5002078363758

In [99]:
np.random.choice(100, 10)

array([10, 71, 36, 15, 89, 17, 35, 80, 55, 18])

In [100]:
np.random.choice([1,2,3,4,5,6,7,8,9,10], size=(3,3))

array([[ 7,  9,  2],
       [ 6,  4,  6],
       [ 3, 10,  6]])

In [102]:
np.random.choice([2,5,7,1,0], size=(3,3), p=[0.1, 0.5, 0.3, 0.1, 0])

array([[7, 7, 2],
       [5, 5, 5],
       [7, 5, 5]])

In [103]:
a = np.array([3,6,3,1,0, 11])
a

array([ 3,  6,  3,  1,  0, 11])

In [104]:
np.random.shuffle(a)

In [105]:
a

array([ 3,  0,  6,  3, 11,  1])

In [110]:
b = np.random.random((3,3))
b

array([[0.67427   , 0.40258793, 0.73882023],
       [0.64832862, 0.89540991, 0.27323692],
       [0.99583515, 0.4000311 , 0.75897992]])

In [112]:
np.random.permutation(b)

array([[0.64832862, 0.89540991, 0.27323692],
       [0.99583515, 0.4000311 , 0.75897992],
       [0.67427   , 0.40258793, 0.73882023]])

### Append, Insert ans delete, sort

In [133]:
np.append([2,3], [[4,5], [1, 3]])

array([2, 3, 4, 5, 1, 3])

In [132]:
np.append([2, 3, 1], [[4, 5], [1,3]])

array([2, 3, 1, 4, 5, 1, 3])

In [134]:
np.append([[1,3,5], [4,3,6]], [[1,2,3]])

array([1, 3, 5, 4, 3, 6, 1, 2, 3])

In [135]:
np.append([[1,3,5], [4,3,6]], [[1,2,3]], axis=0)

array([[1, 3, 5],
       [4, 3, 6],
       [1, 2, 3]])

#### Insert

In [144]:
a = np.array([[2, 2], [3, 4], [5, 6]])
a

array([[2, 2],
       [3, 4],
       [5, 6]])

In [145]:
np.insert(a, 0, 5)

array([5, 2, 2, 3, 4, 5, 6])

In [146]:
np.insert(a, 0, 5, axis=1)

array([[5, 2, 2],
       [5, 3, 4],
       [5, 5, 6]])

In [147]:
np.insert(a, 0, 5, axis=0)

array([[5, 5],
       [2, 2],
       [3, 4],
       [5, 6]])

In [149]:
np.insert(a, [1], [[1], [2], [3]], axis=1)

array([[2, 1, 2],
       [3, 2, 4],
       [5, 3, 6]])

In [151]:
b = a.flatten()
b

array([2, 2, 3, 4, 5, 6])

In [152]:
np.insert(b, [2,2], [5,6])

array([2, 2, 5, 6, 3, 4, 5, 6])

In [153]:
np.insert(b, slice(2, 4), [5, 6])

array([2, 2, 5, 3, 6, 4, 5, 6])

### Delete

In [192]:
a= np.array([[1,3,2,6], [4,1,6,7], [9, 10, 6, 3]])
a

array([[ 1,  3,  2,  6],
       [ 4,  1,  6,  7],
       [ 9, 10,  6,  3]])

In [186]:
a.flatten()

array([ 1,  3,  2,  6,  4,  1,  6,  7,  9, 10,  6,  3])

In [163]:
np.delete(a, [1, 2, 5])

array([ 1,  6,  4,  6,  7,  9, 10,  6,  3])

In [164]:
arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [188]:
np.delete(a, 1, 1)

array([[1, 2, 6],
       [4, 6, 7],
       [9, 6, 3]])

In [191]:
np.delete(a, 2, 1)

array([[ 1,  3,  6],
       [ 4,  1,  7],
       [ 9, 10,  3]])

In [189]:
np.delete(a, 1, 0)

array([[ 1,  3,  2,  6],
       [ 9, 10,  6,  3]])

### Sort

In [196]:
a

array([[ 1,  3,  2,  6],
       [ 4,  1,  6,  7],
       [ 9, 10,  6,  3]])

In [197]:
np.sort(a)

array([[ 1,  2,  3,  6],
       [ 1,  4,  6,  7],
       [ 3,  6,  9, 10]])

In [198]:
np.sort(a, axis=None)

array([ 1,  1,  2,  3,  3,  4,  6,  6,  6,  7,  9, 10])

In [194]:
np.sort(a, axis=0)

array([[ 1,  1,  2,  3],
       [ 4,  3,  6,  6],
       [ 9, 10,  6,  7]])

In [199]:
np.sort(a, axis=1)

array([[ 1,  2,  3,  6],
       [ 1,  4,  6,  7],
       [ 3,  6,  9, 10]])

### Flip

In [175]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [176]:
np.flip(arr, 0)

array([[ 9, 10, 11, 12],
       [ 5,  6,  7,  8],
       [ 1,  2,  3,  4]])

In [177]:
np.flip(arr, 1)

array([[ 4,  3,  2,  1],
       [ 8,  7,  6,  5],
       [12, 11, 10,  9]])

In [180]:
arr.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

### Save

In [183]:
np.save('arrfile', arr)

In [184]:
np.load('arrfile.npy')

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])